# Generated by Django 2.2.7 on 2020-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempAPP', '0002_auto_20200212_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tag',
            field=models.ManyToManyField(to='tempAPP.Tag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(to='tempAPP.Role'),
        ),
    ]
