# Generated by Django 2.2.7 on 2020-02-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempAPP', '0003_auto_20200212_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '账号'},
        ),
    ]
