# Generated by Django 2.2.7 on 2020-02-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempAPP', '0004_auto_20200213_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempData', models.SmallIntegerField(verbose_name='温度')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '温度',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text='<a href="password/reset/">密码重置</a>', max_length=128, verbose_name='password'),
        ),
    ]
