# Generated by Django 2.2.7 on 2020-02-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempAPP', '0005_auto_20200217_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='tempData',
            field=models.CharField(max_length=32, verbose_name='温度'),
        ),
    ]
