# Generated by Django 2.2.7 on 2020-02-17 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempAPP', '0006_auto_20200217_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
