# Generated by Django 2.2.7 on 2020-02-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempAPP', '0007_temperature_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('tempAPP_查看所有项目', '11'),), 'verbose_name': '账号'},
        ),
    ]
